// Code generated by MockGen. DO NOT EDIT.
// Source: api.go

// Package api is a generated GoMock package.
package api

import (
	context "context"
	http "net/http"
	reflect "reflect"
	datastruct "shopapi/internal/datastruct"

	gomock "github.com/golang/mock/gomock"
)

// MockIClientService is a mock of IClientService interface.
type MockIClientService struct {
	ctrl     *gomock.Controller
	recorder *MockIClientServiceMockRecorder
}

// MockIClientServiceMockRecorder is the mock recorder for MockIClientService.
type MockIClientServiceMockRecorder struct {
	mock *MockIClientService
}

// NewMockIClientService creates a new mock instance.
func NewMockIClientService(ctrl *gomock.Controller) *MockIClientService {
	mock := &MockIClientService{ctrl: ctrl}
	mock.recorder = &MockIClientServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClientService) EXPECT() *MockIClientServiceMockRecorder {
	return m.recorder
}

// AddClient mocks base method.
func (m *MockIClientService) AddClient(arg0 *datastruct.AddClientRequest) *datastruct.AddClientResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddClient", arg0)
	ret0, _ := ret[0].(*datastruct.AddClientResponse)
	return ret0
}

// AddClient indicates an expected call of AddClient.
func (mr *MockIClientServiceMockRecorder) AddClient(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddClient", reflect.TypeOf((*MockIClientService)(nil).AddClient), arg0)
}

// DeleteClient mocks base method.
func (m *MockIClientService) DeleteClient(arg0 *datastruct.DeleteClientRequest) *datastruct.DeleteClientResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClient", arg0)
	ret0, _ := ret[0].(*datastruct.DeleteClientResponse)
	return ret0
}

// DeleteClient indicates an expected call of DeleteClient.
func (mr *MockIClientServiceMockRecorder) DeleteClient(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClient", reflect.TypeOf((*MockIClientService)(nil).DeleteClient), arg0)
}

// GetClients mocks base method.
func (m *MockIClientService) GetClients(arg0 *datastruct.GetClientsRequest) *datastruct.GetClientsResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClients", arg0)
	ret0, _ := ret[0].(*datastruct.GetClientsResponse)
	return ret0
}

// GetClients indicates an expected call of GetClients.
func (mr *MockIClientServiceMockRecorder) GetClients(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClients", reflect.TypeOf((*MockIClientService)(nil).GetClients), arg0)
}

// GetClientsByName mocks base method.
func (m *MockIClientService) GetClientsByName(arg0 *datastruct.GetClientsByNameRequest) *datastruct.GetClientsByNameResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientsByName", arg0)
	ret0, _ := ret[0].(*datastruct.GetClientsByNameResponse)
	return ret0
}

// GetClientsByName indicates an expected call of GetClientsByName.
func (mr *MockIClientServiceMockRecorder) GetClientsByName(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientsByName", reflect.TypeOf((*MockIClientService)(nil).GetClientsByName), arg0)
}

// PatchClientAddress mocks base method.
func (m *MockIClientService) PatchClientAddress(arg0 *datastruct.PatchClientAddressRequest) *datastruct.PatchClientAddressResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchClientAddress", arg0)
	ret0, _ := ret[0].(*datastruct.PatchClientAddressResponse)
	return ret0
}

// PatchClientAddress indicates an expected call of PatchClientAddress.
func (mr *MockIClientServiceMockRecorder) PatchClientAddress(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchClientAddress", reflect.TypeOf((*MockIClientService)(nil).PatchClientAddress), arg0)
}

// MockIProductService is a mock of IProductService interface.
type MockIProductService struct {
	ctrl     *gomock.Controller
	recorder *MockIProductServiceMockRecorder
}

// MockIProductServiceMockRecorder is the mock recorder for MockIProductService.
type MockIProductServiceMockRecorder struct {
	mock *MockIProductService
}

// NewMockIProductService creates a new mock instance.
func NewMockIProductService(ctrl *gomock.Controller) *MockIProductService {
	mock := &MockIProductService{ctrl: ctrl}
	mock.recorder = &MockIProductServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProductService) EXPECT() *MockIProductServiceMockRecorder {
	return m.recorder
}

// AddProduct mocks base method.
func (m *MockIProductService) AddProduct(arg0 *datastruct.AddProductRequest) *datastruct.AddProductResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProduct", arg0)
	ret0, _ := ret[0].(*datastruct.AddProductResponse)
	return ret0
}

// AddProduct indicates an expected call of AddProduct.
func (mr *MockIProductServiceMockRecorder) AddProduct(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProduct", reflect.TypeOf((*MockIProductService)(nil).AddProduct), arg0)
}

// DecreaseProducts mocks base method.
func (m *MockIProductService) DecreaseProducts(arg0 *datastruct.DecreaseProductsRequest) *datastruct.DecreaseProductsResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecreaseProducts", arg0)
	ret0, _ := ret[0].(*datastruct.DecreaseProductsResponse)
	return ret0
}

// DecreaseProducts indicates an expected call of DecreaseProducts.
func (mr *MockIProductServiceMockRecorder) DecreaseProducts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecreaseProducts", reflect.TypeOf((*MockIProductService)(nil).DecreaseProducts), arg0)
}

// DeleteProduct mocks base method.
func (m *MockIProductService) DeleteProduct(arg0 *datastruct.DeleteProductRequest) *datastruct.DeleteProductResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", arg0)
	ret0, _ := ret[0].(*datastruct.DeleteProductResponse)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockIProductServiceMockRecorder) DeleteProduct(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockIProductService)(nil).DeleteProduct), arg0)
}

// GetProduct mocks base method.
func (m *MockIProductService) GetProduct(arg0 *datastruct.GetProductRequest) *datastruct.GetProductResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", arg0)
	ret0, _ := ret[0].(*datastruct.GetProductResponse)
	return ret0
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockIProductServiceMockRecorder) GetProduct(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockIProductService)(nil).GetProduct), arg0)
}

// GetProducts mocks base method.
func (m *MockIProductService) GetProducts(arg0 *datastruct.GetProductsRequest) *datastruct.GetProductsResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProducts", arg0)
	ret0, _ := ret[0].(*datastruct.GetProductsResponse)
	return ret0
}

// GetProducts indicates an expected call of GetProducts.
func (mr *MockIProductServiceMockRecorder) GetProducts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProducts", reflect.TypeOf((*MockIProductService)(nil).GetProducts), arg0)
}

// MockISupplierService is a mock of ISupplierService interface.
type MockISupplierService struct {
	ctrl     *gomock.Controller
	recorder *MockISupplierServiceMockRecorder
}

// MockISupplierServiceMockRecorder is the mock recorder for MockISupplierService.
type MockISupplierServiceMockRecorder struct {
	mock *MockISupplierService
}

// NewMockISupplierService creates a new mock instance.
func NewMockISupplierService(ctrl *gomock.Controller) *MockISupplierService {
	mock := &MockISupplierService{ctrl: ctrl}
	mock.recorder = &MockISupplierServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISupplierService) EXPECT() *MockISupplierServiceMockRecorder {
	return m.recorder
}

// AddSupplier mocks base method.
func (m *MockISupplierService) AddSupplier(arg0 *datastruct.AddSupplierRequest) *datastruct.AddSupplierResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSupplier", arg0)
	ret0, _ := ret[0].(*datastruct.AddSupplierResponse)
	return ret0
}

// AddSupplier indicates an expected call of AddSupplier.
func (mr *MockISupplierServiceMockRecorder) AddSupplier(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSupplier", reflect.TypeOf((*MockISupplierService)(nil).AddSupplier), arg0)
}

// DeleteSupplier mocks base method.
func (m *MockISupplierService) DeleteSupplier(arg0 *datastruct.DeleteSupplierRequest) *datastruct.DeleteSupplierResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSupplier", arg0)
	ret0, _ := ret[0].(*datastruct.DeleteSupplierResponse)
	return ret0
}

// DeleteSupplier indicates an expected call of DeleteSupplier.
func (mr *MockISupplierServiceMockRecorder) DeleteSupplier(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSupplier", reflect.TypeOf((*MockISupplierService)(nil).DeleteSupplier), arg0)
}

// GetSupplier mocks base method.
func (m *MockISupplierService) GetSupplier(arg0 *datastruct.GetSupplierRequest) *datastruct.GetSupplierResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupplier", arg0)
	ret0, _ := ret[0].(*datastruct.GetSupplierResponse)
	return ret0
}

// GetSupplier indicates an expected call of GetSupplier.
func (mr *MockISupplierServiceMockRecorder) GetSupplier(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupplier", reflect.TypeOf((*MockISupplierService)(nil).GetSupplier), arg0)
}

// GetSuppliers mocks base method.
func (m *MockISupplierService) GetSuppliers(arg0 *datastruct.GetSuppliersRequest) *datastruct.GetSuppliersResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuppliers", arg0)
	ret0, _ := ret[0].(*datastruct.GetSuppliersResponse)
	return ret0
}

// GetSuppliers indicates an expected call of GetSuppliers.
func (mr *MockISupplierServiceMockRecorder) GetSuppliers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuppliers", reflect.TypeOf((*MockISupplierService)(nil).GetSuppliers), arg0)
}

// UpdateSupplierAddress mocks base method.
func (m *MockISupplierService) UpdateSupplierAddress(arg0 *datastruct.UpdateSupplierAddressRequest) *datastruct.UpdateSupplierAddressResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSupplierAddress", arg0)
	ret0, _ := ret[0].(*datastruct.UpdateSupplierAddressResponse)
	return ret0
}

// UpdateSupplierAddress indicates an expected call of UpdateSupplierAddress.
func (mr *MockISupplierServiceMockRecorder) UpdateSupplierAddress(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSupplierAddress", reflect.TypeOf((*MockISupplierService)(nil).UpdateSupplierAddress), arg0)
}

// MockIImageService is a mock of IImageService interface.
type MockIImageService struct {
	ctrl     *gomock.Controller
	recorder *MockIImageServiceMockRecorder
}

// MockIImageServiceMockRecorder is the mock recorder for MockIImageService.
type MockIImageServiceMockRecorder struct {
	mock *MockIImageService
}

// NewMockIImageService creates a new mock instance.
func NewMockIImageService(ctrl *gomock.Controller) *MockIImageService {
	mock := &MockIImageService{ctrl: ctrl}
	mock.recorder = &MockIImageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIImageService) EXPECT() *MockIImageServiceMockRecorder {
	return m.recorder
}

// AddImage mocks base method.
func (m *MockIImageService) AddImage(arg0 *datastruct.AddImageRequest) *datastruct.AddImageResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddImage", arg0)
	ret0, _ := ret[0].(*datastruct.AddImageResponse)
	return ret0
}

// AddImage indicates an expected call of AddImage.
func (mr *MockIImageServiceMockRecorder) AddImage(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddImage", reflect.TypeOf((*MockIImageService)(nil).AddImage), arg0)
}

// DeleteImage mocks base method.
func (m *MockIImageService) DeleteImage(arg0 *datastruct.DeleteImageRequest) *datastruct.DeleteImageResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImage", arg0)
	ret0, _ := ret[0].(*datastruct.DeleteImageResponse)
	return ret0
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockIImageServiceMockRecorder) DeleteImage(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockIImageService)(nil).DeleteImage), arg0)
}

// GetImage mocks base method.
func (m *MockIImageService) GetImage(arg0 *datastruct.GetImageRequest) *datastruct.GetImageResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", arg0)
	ret0, _ := ret[0].(*datastruct.GetImageResponse)
	return ret0
}

// GetImage indicates an expected call of GetImage.
func (mr *MockIImageServiceMockRecorder) GetImage(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockIImageService)(nil).GetImage), arg0)
}

// GetProductImage mocks base method.
func (m *MockIImageService) GetProductImage(arg0 *datastruct.GetProductImageRequest) *datastruct.GetProductImageResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductImage", arg0)
	ret0, _ := ret[0].(*datastruct.GetProductImageResponse)
	return ret0
}

// GetProductImage indicates an expected call of GetProductImage.
func (mr *MockIImageServiceMockRecorder) GetProductImage(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductImage", reflect.TypeOf((*MockIImageService)(nil).GetProductImage), arg0)
}

// UpdateImage mocks base method.
func (m *MockIImageService) UpdateImage(arg0 *datastruct.UpdateImageRequest) *datastruct.UpdateImageResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateImage", arg0)
	ret0, _ := ret[0].(*datastruct.UpdateImageResponse)
	return ret0
}

// UpdateImage indicates an expected call of UpdateImage.
func (mr *MockIImageServiceMockRecorder) UpdateImage(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateImage", reflect.TypeOf((*MockIImageService)(nil).UpdateImage), arg0)
}

// MockIWithStatus is a mock of IWithStatus interface.
type MockIWithStatus struct {
	ctrl     *gomock.Controller
	recorder *MockIWithStatusMockRecorder
}

// MockIWithStatusMockRecorder is the mock recorder for MockIWithStatus.
type MockIWithStatusMockRecorder struct {
	mock *MockIWithStatus
}

// NewMockIWithStatus creates a new mock instance.
func NewMockIWithStatus(ctrl *gomock.Controller) *MockIWithStatus {
	mock := &MockIWithStatus{ctrl: ctrl}
	mock.recorder = &MockIWithStatusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWithStatus) EXPECT() *MockIWithStatusMockRecorder {
	return m.recorder
}

// GetStatus mocks base method.
func (m *MockIWithStatus) GetStatus() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockIWithStatusMockRecorder) GetStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockIWithStatus)(nil).GetStatus))
}

// MockIServer is a mock of IServer interface.
type MockIServer struct {
	ctrl     *gomock.Controller
	recorder *MockIServerMockRecorder
}

// MockIServerMockRecorder is the mock recorder for MockIServer.
type MockIServerMockRecorder struct {
	mock *MockIServer
}

// NewMockIServer creates a new mock instance.
func NewMockIServer(ctrl *gomock.Controller) *MockIServer {
	mock := &MockIServer{ctrl: ctrl}
	mock.recorder = &MockIServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIServer) EXPECT() *MockIServerMockRecorder {
	return m.recorder
}

// ListenAndServe mocks base method.
func (m *MockIServer) ListenAndServe() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenAndServe")
	ret0, _ := ret[0].(error)
	return ret0
}

// ListenAndServe indicates an expected call of ListenAndServe.
func (mr *MockIServerMockRecorder) ListenAndServe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenAndServe", reflect.TypeOf((*MockIServer)(nil).ListenAndServe))
}

// Shutdown mocks base method.
func (m *MockIServer) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockIServerMockRecorder) Shutdown(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockIServer)(nil).Shutdown), ctx)
}

// MockIRouter is a mock of IRouter interface.
type MockIRouter struct {
	ctrl     *gomock.Controller
	recorder *MockIRouterMockRecorder
}

// MockIRouterMockRecorder is the mock recorder for MockIRouter.
type MockIRouterMockRecorder struct {
	mock *MockIRouter
}

// NewMockIRouter creates a new mock instance.
func NewMockIRouter(ctrl *gomock.Controller) *MockIRouter {
	mock := &MockIRouter{ctrl: ctrl}
	mock.recorder = &MockIRouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRouter) EXPECT() *MockIRouterMockRecorder {
	return m.recorder
}

// HandleFunc mocks base method.
func (m *MockIRouter) HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleFunc", pattern, handler)
}

// HandleFunc indicates an expected call of HandleFunc.
func (mr *MockIRouterMockRecorder) HandleFunc(pattern, handler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleFunc", reflect.TypeOf((*MockIRouter)(nil).HandleFunc), pattern, handler)
}
