// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: images.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addImage = `-- name: AddImage :one
INSERT INTO images (uid, image)
VALUES ($1, $2)
ON CONFLICT (uid) DO NOTHING
RETURNING uid
`

type AddImageParams struct {
	Uid   uuid.UUID
	Image []byte
}

func (q *Queries) AddImage(ctx context.Context, arg AddImageParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, addImage, arg.Uid, arg.Image)
	var uid uuid.UUID
	err := row.Scan(&uid)
	return uid, err
}

const deleteImage = `-- name: DeleteImage :one
DELETE FROM images
WHERE uid = $1
RETURNING uid
`

func (q *Queries) DeleteImage(ctx context.Context, uid uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteImage, uid)
	err := row.Scan(&uid)
	return uid, err
}

const getImage = `-- name: GetImage :one
SELECT image FROM images
WHERE uid = $1
`

func (q *Queries) GetImage(ctx context.Context, uid uuid.UUID) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getImage, uid)
	var image []byte
	err := row.Scan(&image)
	return image, err
}

const getProductImage = `-- name: GetProductImage :one
SELECT uid, image FROM images i
WHERE i.uid = (SELECT image_id FROM products p WHERE p.uid = $1)
`

func (q *Queries) GetProductImage(ctx context.Context, uid uuid.UUID) (Image, error) {
	row := q.db.QueryRowContext(ctx, getProductImage, uid)
	var i Image
	err := row.Scan(&i.Uid, &i.Image)
	return i, err
}

const updateImage = `-- name: UpdateImage :one
UPDATE images
SET image = $1
WHERE uid = $2
RETURNING uid
`

type UpdateImageParams struct {
	Image []byte
	Uid   uuid.UUID
}

func (q *Queries) UpdateImage(ctx context.Context, arg UpdateImageParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, updateImage, arg.Image, arg.Uid)
	var uid uuid.UUID
	err := row.Scan(&uid)
	return uid, err
}
