// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Address struct {
	ID      int32
	Country string
	City    string
	Street  string
}

type Client struct {
	Uid              uuid.UUID
	ClientName       string
	ClientSurname    string
	Birthday         time.Time
	Gender           string
	RegistrationDate time.Time
	AddressID        int32
}

type ClientDetail struct {
	ClientName       string
	ClientSurname    string
	Birthday         time.Time
	Gender           string
	Uid              uuid.UUID
	RegistrationDate time.Time
	Country          string
	City             string
	Street           string
}

type Image struct {
	Uid   uuid.UUID
	Image []byte
}

type Product struct {
	Uid            uuid.UUID
	Name           string
	Category       string
	Price          int64
	AvailableStock int64
	LastUpdateDate time.Time
	SupplierID     uuid.UUID
	ImageID        uuid.UUID
}

type Supplier struct {
	Uid         uuid.UUID
	Name        string
	PhoneNumber string
	AddressID   int32
}

type SupplierDetail struct {
	Uid         uuid.UUID
	Name        string
	PhoneNumber string
	Country     string
	City        string
	Street      string
}
