// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddImage(ctx context.Context, arg AddImageParams) (uuid.UUID, error)
	CalculateClientsWithAddress(ctx context.Context, addressID int32) (int64, error)
	CalculateSuppliersWithAddress(ctx context.Context, addressID int32) (int64, error)
	DecreaseProduct(ctx context.Context, arg DecreaseProductParams) (int64, error)
	DeleteAddress(ctx context.Context, id int32) error
	DeleteClient(ctx context.Context, uid uuid.UUID) (int32, error)
	DeleteImage(ctx context.Context, uid uuid.UUID) (uuid.UUID, error)
	DeleteProduct(ctx context.Context, uid uuid.UUID) (uuid.UUID, error)
	DeleteSupplier(ctx context.Context, uid uuid.UUID) (int32, error)
	GetAllClients(ctx context.Context) ([]ClientDetail, error)
	GetAllProducts(ctx context.Context) ([]Product, error)
	GetAllSuppliers(ctx context.Context) ([]SupplierDetail, error)
	GetClientsPage(ctx context.Context, arg GetClientsPageParams) ([]ClientDetail, error)
	GetClientsWithName(ctx context.Context, arg GetClientsWithNameParams) ([]ClientDetail, error)
	GetImage(ctx context.Context, uid uuid.UUID) ([]byte, error)
	GetProduct(ctx context.Context, uid uuid.UUID) (Product, error)
	GetProductImage(ctx context.Context, uid uuid.UUID) (Image, error)
	GetProductsPage(ctx context.Context, arg GetProductsPageParams) ([]Product, error)
	GetSupplier(ctx context.Context, uid uuid.UUID) (SupplierDetail, error)
	GetSuppliersPage(ctx context.Context, arg GetSuppliersPageParams) ([]SupplierDetail, error)
	InsertAddress(ctx context.Context, arg InsertAddressParams) (int32, error)
	InsertClient(ctx context.Context, arg InsertClientParams) (uuid.UUID, error)
	InsertProduct(ctx context.Context, arg InsertProductParams) (uuid.UUID, error)
	InsertSupplier(ctx context.Context, arg InsertSupplierParams) (uuid.UUID, error)
	IsImageAndSupplierExists(ctx context.Context, arg IsImageAndSupplierExistsParams) (bool, error)
	LockStockForUpdate(ctx context.Context, uid uuid.UUID) (int64, error)
	UpdateClientAddress(ctx context.Context, arg UpdateClientAddressParams) (int32, error)
	UpdateImage(ctx context.Context, arg UpdateImageParams) (uuid.UUID, error)
	UpdateSupplierAddress(ctx context.Context, arg UpdateSupplierAddressParams) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
