// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: suppliers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const calculateSuppliersWithAddress = `-- name: CalculateSuppliersWithAddress :one
SELECT COUNT(*) as suppliersAmount
FROM suppliers
WHERE address_id = $1
`

func (q *Queries) CalculateSuppliersWithAddress(ctx context.Context, addressID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, calculateSuppliersWithAddress, addressID)
	var suppliersamount int64
	err := row.Scan(&suppliersamount)
	return suppliersamount, err
}

const deleteSupplier = `-- name: DeleteSupplier :one
DELETE FROM suppliers s
WHERE s.uid = $1
RETURNING s.address_id
`

func (q *Queries) DeleteSupplier(ctx context.Context, uid uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, deleteSupplier, uid)
	var address_id int32
	err := row.Scan(&address_id)
	return address_id, err
}

const getAllSuppliers = `-- name: GetAllSuppliers :many
SELECT uid, name, phone_number, country, city, street
FROM supplier_details
ORDER BY uid
`

func (q *Queries) GetAllSuppliers(ctx context.Context) ([]SupplierDetail, error) {
	rows, err := q.db.QueryContext(ctx, getAllSuppliers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplierDetail
	for rows.Next() {
		var i SupplierDetail
		if err := rows.Scan(
			&i.Uid,
			&i.Name,
			&i.PhoneNumber,
			&i.Country,
			&i.City,
			&i.Street,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSupplier = `-- name: GetSupplier :one
SELECT uid, name, phone_number, country, city, street
FROM supplier_details
WHERE uid = $1
`

func (q *Queries) GetSupplier(ctx context.Context, uid uuid.UUID) (SupplierDetail, error) {
	row := q.db.QueryRowContext(ctx, getSupplier, uid)
	var i SupplierDetail
	err := row.Scan(
		&i.Uid,
		&i.Name,
		&i.PhoneNumber,
		&i.Country,
		&i.City,
		&i.Street,
	)
	return i, err
}

const getSuppliersPage = `-- name: GetSuppliersPage :many
SELECT uid, name, phone_number, country, city, street
FROM supplier_details
ORDER BY uid
OFFSET $1
LIMIT $2
`

type GetSuppliersPageParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) GetSuppliersPage(ctx context.Context, arg GetSuppliersPageParams) ([]SupplierDetail, error) {
	rows, err := q.db.QueryContext(ctx, getSuppliersPage, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplierDetail
	for rows.Next() {
		var i SupplierDetail
		if err := rows.Scan(
			&i.Uid,
			&i.Name,
			&i.PhoneNumber,
			&i.Country,
			&i.City,
			&i.Street,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSupplier = `-- name: InsertSupplier :one
INSERT INTO suppliers (uid, name, phone_number, address_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (uid)
DO NOTHING
RETURNING uid
`

type InsertSupplierParams struct {
	Uid         uuid.UUID
	Name        string
	PhoneNumber string
	AddressID   int32
}

func (q *Queries) InsertSupplier(ctx context.Context, arg InsertSupplierParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insertSupplier,
		arg.Uid,
		arg.Name,
		arg.PhoneNumber,
		arg.AddressID,
	)
	var uid uuid.UUID
	err := row.Scan(&uid)
	return uid, err
}

const updateSupplierAddress = `-- name: UpdateSupplierAddress :one
UPDATE suppliers
SET address_id = $1
WHERE uid = $2
RETURNING uid
`

type UpdateSupplierAddressParams struct {
	AddressID int32
	Uid       uuid.UUID
}

func (q *Queries) UpdateSupplierAddress(ctx context.Context, arg UpdateSupplierAddressParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, updateSupplierAddress, arg.AddressID, arg.Uid)
	var uid uuid.UUID
	err := row.Scan(&uid)
	return uid, err
}
