// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"
	datastruct "shopapi/internal/datastruct"

	gomock "github.com/golang/mock/gomock"
)

// MockILogger is a mock of ILogger interface.
type MockILogger struct {
	ctrl     *gomock.Controller
	recorder *MockILoggerMockRecorder
}

// MockILoggerMockRecorder is the mock recorder for MockILogger.
type MockILoggerMockRecorder struct {
	mock *MockILogger
}

// NewMockILogger creates a new mock instance.
func NewMockILogger(ctrl *gomock.Controller) *MockILogger {
	mock := &MockILogger{ctrl: ctrl}
	mock.recorder = &MockILoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILogger) EXPECT() *MockILoggerMockRecorder {
	return m.recorder
}

// ErrorKV mocks base method.
func (m *MockILogger) ErrorKV(message string, argsKV ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{message}
	for _, a := range argsKV {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ErrorKV", varargs...)
}

// ErrorKV indicates an expected call of ErrorKV.
func (mr *MockILoggerMockRecorder) ErrorKV(message interface{}, argsKV ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{message}, argsKV...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorKV", reflect.TypeOf((*MockILogger)(nil).ErrorKV), varargs...)
}

// Errorf mocks base method.
func (m *MockILogger) Errorf(message string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{message}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Errorf", varargs...)
}

// Errorf indicates an expected call of Errorf.
func (mr *MockILoggerMockRecorder) Errorf(message interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{message}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorf", reflect.TypeOf((*MockILogger)(nil).Errorf), varargs...)
}

// FatalKV mocks base method.
func (m *MockILogger) FatalKV(message string, argsKV ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{message}
	for _, a := range argsKV {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "FatalKV", varargs...)
}

// FatalKV indicates an expected call of FatalKV.
func (mr *MockILoggerMockRecorder) FatalKV(message interface{}, argsKV ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{message}, argsKV...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FatalKV", reflect.TypeOf((*MockILogger)(nil).FatalKV), varargs...)
}

// Fatalf mocks base method.
func (m *MockILogger) Fatalf(message string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{message}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Fatalf", varargs...)
}

// Fatalf indicates an expected call of Fatalf.
func (mr *MockILoggerMockRecorder) Fatalf(message interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{message}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatalf", reflect.TypeOf((*MockILogger)(nil).Fatalf), varargs...)
}

// InfoKV mocks base method.
func (m *MockILogger) InfoKV(message string, argsKV ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{message}
	for _, a := range argsKV {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "InfoKV", varargs...)
}

// InfoKV indicates an expected call of InfoKV.
func (mr *MockILoggerMockRecorder) InfoKV(message interface{}, argsKV ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{message}, argsKV...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoKV", reflect.TypeOf((*MockILogger)(nil).InfoKV), varargs...)
}

// Infof mocks base method.
func (m *MockILogger) Infof(message string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{message}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Infof", varargs...)
}

// Infof indicates an expected call of Infof.
func (mr *MockILoggerMockRecorder) Infof(message interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{message}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infof", reflect.TypeOf((*MockILogger)(nil).Infof), varargs...)
}

// WarnKV mocks base method.
func (m *MockILogger) WarnKV(message string, argsKV ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{message}
	for _, a := range argsKV {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "WarnKV", varargs...)
}

// WarnKV indicates an expected call of WarnKV.
func (mr *MockILoggerMockRecorder) WarnKV(message interface{}, argsKV ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{message}, argsKV...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WarnKV", reflect.TypeOf((*MockILogger)(nil).WarnKV), varargs...)
}

// Warnf mocks base method.
func (m *MockILogger) Warnf(message string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{message}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warnf", varargs...)
}

// Warnf indicates an expected call of Warnf.
func (mr *MockILoggerMockRecorder) Warnf(message interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{message}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warnf", reflect.TypeOf((*MockILogger)(nil).Warnf), varargs...)
}

// MockICache is a mock of ICache interface.
type MockICache struct {
	ctrl     *gomock.Controller
	recorder *MockICacheMockRecorder
}

// MockICacheMockRecorder is the mock recorder for MockICache.
type MockICacheMockRecorder struct {
	mock *MockICache
}

// NewMockICache creates a new mock instance.
func NewMockICache(ctrl *gomock.Controller) *MockICache {
	mock := &MockICache{ctrl: ctrl}
	mock.recorder = &MockICacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICache) EXPECT() *MockICacheMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockICache) Read(key string, v any) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", key, v)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockICacheMockRecorder) Read(key, v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockICache)(nil).Read), key, v)
}

// Write mocks base method.
func (m *MockICache) Write(key string, v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", key, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockICacheMockRecorder) Write(key, v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockICache)(nil).Write), key, v)
}

// MockICachedState is a mock of ICachedState interface.
type MockICachedState struct {
	ctrl     *gomock.Controller
	recorder *MockICachedStateMockRecorder
}

// MockICachedStateMockRecorder is the mock recorder for MockICachedState.
type MockICachedStateMockRecorder struct {
	mock *MockICachedState
}

// NewMockICachedState creates a new mock instance.
func NewMockICachedState(ctrl *gomock.Controller) *MockICachedState {
	mock := &MockICachedState{ctrl: ctrl}
	mock.recorder = &MockICachedStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICachedState) EXPECT() *MockICachedStateMockRecorder {
	return m.recorder
}

// SetCached mocks base method.
func (m *MockICachedState) SetCached(arg0 bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCached", arg0)
}

// SetCached indicates an expected call of SetCached.
func (mr *MockICachedStateMockRecorder) SetCached(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCached", reflect.TypeOf((*MockICachedState)(nil).SetCached), arg0)
}

// MockIClientStorage is a mock of IClientStorage interface.
type MockIClientStorage struct {
	ctrl     *gomock.Controller
	recorder *MockIClientStorageMockRecorder
}

// MockIClientStorageMockRecorder is the mock recorder for MockIClientStorage.
type MockIClientStorageMockRecorder struct {
	mock *MockIClientStorage
}

// NewMockIClientStorage creates a new mock instance.
func NewMockIClientStorage(ctrl *gomock.Controller) *MockIClientStorage {
	mock := &MockIClientStorage{ctrl: ctrl}
	mock.recorder = &MockIClientStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClientStorage) EXPECT() *MockIClientStorageMockRecorder {
	return m.recorder
}

// AddClient mocks base method.
func (m *MockIClientStorage) AddClient(arg0 *datastruct.AddClientRequest) (*datastruct.AddClientResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddClient", arg0)
	ret0, _ := ret[0].(*datastruct.AddClientResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddClient indicates an expected call of AddClient.
func (mr *MockIClientStorageMockRecorder) AddClient(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddClient", reflect.TypeOf((*MockIClientStorage)(nil).AddClient), arg0)
}

// DeleteClient mocks base method.
func (m *MockIClientStorage) DeleteClient(arg0 *datastruct.DeleteClientRequest) (*datastruct.DeleteClientResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClient", arg0)
	ret0, _ := ret[0].(*datastruct.DeleteClientResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteClient indicates an expected call of DeleteClient.
func (mr *MockIClientStorageMockRecorder) DeleteClient(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClient", reflect.TypeOf((*MockIClientStorage)(nil).DeleteClient), arg0)
}

// GetClients mocks base method.
func (m *MockIClientStorage) GetClients(arg0 *datastruct.GetClientsRequest) (*datastruct.GetClientsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClients", arg0)
	ret0, _ := ret[0].(*datastruct.GetClientsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClients indicates an expected call of GetClients.
func (mr *MockIClientStorageMockRecorder) GetClients(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClients", reflect.TypeOf((*MockIClientStorage)(nil).GetClients), arg0)
}

// GetClientsByName mocks base method.
func (m *MockIClientStorage) GetClientsByName(arg0 *datastruct.GetClientsByNameRequest) (*datastruct.GetClientsByNameResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientsByName", arg0)
	ret0, _ := ret[0].(*datastruct.GetClientsByNameResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientsByName indicates an expected call of GetClientsByName.
func (mr *MockIClientStorageMockRecorder) GetClientsByName(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientsByName", reflect.TypeOf((*MockIClientStorage)(nil).GetClientsByName), arg0)
}

// PatchClientAddress mocks base method.
func (m *MockIClientStorage) PatchClientAddress(arg0 *datastruct.PatchClientAddressRequest) (*datastruct.PatchClientAddressResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchClientAddress", arg0)
	ret0, _ := ret[0].(*datastruct.PatchClientAddressResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchClientAddress indicates an expected call of PatchClientAddress.
func (mr *MockIClientStorageMockRecorder) PatchClientAddress(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchClientAddress", reflect.TypeOf((*MockIClientStorage)(nil).PatchClientAddress), arg0)
}

// MockIProductStorage is a mock of IProductStorage interface.
type MockIProductStorage struct {
	ctrl     *gomock.Controller
	recorder *MockIProductStorageMockRecorder
}

// MockIProductStorageMockRecorder is the mock recorder for MockIProductStorage.
type MockIProductStorageMockRecorder struct {
	mock *MockIProductStorage
}

// NewMockIProductStorage creates a new mock instance.
func NewMockIProductStorage(ctrl *gomock.Controller) *MockIProductStorage {
	mock := &MockIProductStorage{ctrl: ctrl}
	mock.recorder = &MockIProductStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProductStorage) EXPECT() *MockIProductStorageMockRecorder {
	return m.recorder
}

// AddProduct mocks base method.
func (m *MockIProductStorage) AddProduct(arg0 *datastruct.AddProductRequest) (*datastruct.AddProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProduct", arg0)
	ret0, _ := ret[0].(*datastruct.AddProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddProduct indicates an expected call of AddProduct.
func (mr *MockIProductStorageMockRecorder) AddProduct(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProduct", reflect.TypeOf((*MockIProductStorage)(nil).AddProduct), arg0)
}

// DecreaseProducts mocks base method.
func (m *MockIProductStorage) DecreaseProducts(arg0 *datastruct.DecreaseProductsRequest) (*datastruct.DecreaseProductsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecreaseProducts", arg0)
	ret0, _ := ret[0].(*datastruct.DecreaseProductsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecreaseProducts indicates an expected call of DecreaseProducts.
func (mr *MockIProductStorageMockRecorder) DecreaseProducts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecreaseProducts", reflect.TypeOf((*MockIProductStorage)(nil).DecreaseProducts), arg0)
}

// DeleteProduct mocks base method.
func (m *MockIProductStorage) DeleteProduct(arg0 *datastruct.DeleteProductRequest) (*datastruct.DeleteProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", arg0)
	ret0, _ := ret[0].(*datastruct.DeleteProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockIProductStorageMockRecorder) DeleteProduct(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockIProductStorage)(nil).DeleteProduct), arg0)
}

// GetProduct mocks base method.
func (m *MockIProductStorage) GetProduct(arg0 *datastruct.GetProductRequest) (*datastruct.GetProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", arg0)
	ret0, _ := ret[0].(*datastruct.GetProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockIProductStorageMockRecorder) GetProduct(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockIProductStorage)(nil).GetProduct), arg0)
}

// GetProducts mocks base method.
func (m *MockIProductStorage) GetProducts(arg0 *datastruct.GetProductsRequest) (*datastruct.GetProductsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProducts", arg0)
	ret0, _ := ret[0].(*datastruct.GetProductsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProducts indicates an expected call of GetProducts.
func (mr *MockIProductStorageMockRecorder) GetProducts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProducts", reflect.TypeOf((*MockIProductStorage)(nil).GetProducts), arg0)
}

// MockISupplierStorage is a mock of ISupplierStorage interface.
type MockISupplierStorage struct {
	ctrl     *gomock.Controller
	recorder *MockISupplierStorageMockRecorder
}

// MockISupplierStorageMockRecorder is the mock recorder for MockISupplierStorage.
type MockISupplierStorageMockRecorder struct {
	mock *MockISupplierStorage
}

// NewMockISupplierStorage creates a new mock instance.
func NewMockISupplierStorage(ctrl *gomock.Controller) *MockISupplierStorage {
	mock := &MockISupplierStorage{ctrl: ctrl}
	mock.recorder = &MockISupplierStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISupplierStorage) EXPECT() *MockISupplierStorageMockRecorder {
	return m.recorder
}

// AddSupplier mocks base method.
func (m *MockISupplierStorage) AddSupplier(arg0 *datastruct.AddSupplierRequest) (*datastruct.AddSupplierResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSupplier", arg0)
	ret0, _ := ret[0].(*datastruct.AddSupplierResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddSupplier indicates an expected call of AddSupplier.
func (mr *MockISupplierStorageMockRecorder) AddSupplier(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSupplier", reflect.TypeOf((*MockISupplierStorage)(nil).AddSupplier), arg0)
}

// DeleteSupplier mocks base method.
func (m *MockISupplierStorage) DeleteSupplier(arg0 *datastruct.DeleteSupplierRequest) (*datastruct.DeleteSupplierResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSupplier", arg0)
	ret0, _ := ret[0].(*datastruct.DeleteSupplierResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSupplier indicates an expected call of DeleteSupplier.
func (mr *MockISupplierStorageMockRecorder) DeleteSupplier(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSupplier", reflect.TypeOf((*MockISupplierStorage)(nil).DeleteSupplier), arg0)
}

// GetSupplier mocks base method.
func (m *MockISupplierStorage) GetSupplier(arg0 *datastruct.GetSupplierRequest) (*datastruct.GetSupplierResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupplier", arg0)
	ret0, _ := ret[0].(*datastruct.GetSupplierResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSupplier indicates an expected call of GetSupplier.
func (mr *MockISupplierStorageMockRecorder) GetSupplier(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupplier", reflect.TypeOf((*MockISupplierStorage)(nil).GetSupplier), arg0)
}

// GetSuppliers mocks base method.
func (m *MockISupplierStorage) GetSuppliers(arg0 *datastruct.GetSuppliersRequest) (*datastruct.GetSuppliersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuppliers", arg0)
	ret0, _ := ret[0].(*datastruct.GetSuppliersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSuppliers indicates an expected call of GetSuppliers.
func (mr *MockISupplierStorageMockRecorder) GetSuppliers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuppliers", reflect.TypeOf((*MockISupplierStorage)(nil).GetSuppliers), arg0)
}

// UpdateSupplierAddress mocks base method.
func (m *MockISupplierStorage) UpdateSupplierAddress(arg0 *datastruct.UpdateSupplierAddressRequest) (*datastruct.UpdateSupplierAddressResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSupplierAddress", arg0)
	ret0, _ := ret[0].(*datastruct.UpdateSupplierAddressResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSupplierAddress indicates an expected call of UpdateSupplierAddress.
func (mr *MockISupplierStorageMockRecorder) UpdateSupplierAddress(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSupplierAddress", reflect.TypeOf((*MockISupplierStorage)(nil).UpdateSupplierAddress), arg0)
}

// MockIImageStorage is a mock of IImageStorage interface.
type MockIImageStorage struct {
	ctrl     *gomock.Controller
	recorder *MockIImageStorageMockRecorder
}

// MockIImageStorageMockRecorder is the mock recorder for MockIImageStorage.
type MockIImageStorageMockRecorder struct {
	mock *MockIImageStorage
}

// NewMockIImageStorage creates a new mock instance.
func NewMockIImageStorage(ctrl *gomock.Controller) *MockIImageStorage {
	mock := &MockIImageStorage{ctrl: ctrl}
	mock.recorder = &MockIImageStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIImageStorage) EXPECT() *MockIImageStorageMockRecorder {
	return m.recorder
}

// AddImage mocks base method.
func (m *MockIImageStorage) AddImage(arg0 *datastruct.AddImageRequest) (*datastruct.AddImageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddImage", arg0)
	ret0, _ := ret[0].(*datastruct.AddImageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddImage indicates an expected call of AddImage.
func (mr *MockIImageStorageMockRecorder) AddImage(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddImage", reflect.TypeOf((*MockIImageStorage)(nil).AddImage), arg0)
}

// DeleteImage mocks base method.
func (m *MockIImageStorage) DeleteImage(arg0 *datastruct.DeleteImageRequest) (*datastruct.DeleteImageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImage", arg0)
	ret0, _ := ret[0].(*datastruct.DeleteImageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockIImageStorageMockRecorder) DeleteImage(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockIImageStorage)(nil).DeleteImage), arg0)
}

// GetImage mocks base method.
func (m *MockIImageStorage) GetImage(arg0 *datastruct.GetImageRequest) (*datastruct.GetImageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", arg0)
	ret0, _ := ret[0].(*datastruct.GetImageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockIImageStorageMockRecorder) GetImage(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockIImageStorage)(nil).GetImage), arg0)
}

// GetProductImage mocks base method.
func (m *MockIImageStorage) GetProductImage(arg0 *datastruct.GetProductImageRequest) (*datastruct.GetProductImageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductImage", arg0)
	ret0, _ := ret[0].(*datastruct.GetProductImageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductImage indicates an expected call of GetProductImage.
func (mr *MockIImageStorageMockRecorder) GetProductImage(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductImage", reflect.TypeOf((*MockIImageStorage)(nil).GetProductImage), arg0)
}

// UpdateImage mocks base method.
func (m *MockIImageStorage) UpdateImage(arg0 *datastruct.UpdateImageRequest) (*datastruct.UpdateImageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateImage", arg0)
	ret0, _ := ret[0].(*datastruct.UpdateImageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateImage indicates an expected call of UpdateImage.
func (mr *MockIImageStorageMockRecorder) UpdateImage(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateImage", reflect.TypeOf((*MockIImageStorage)(nil).UpdateImage), arg0)
}
