// Code generated by MockGen. DO NOT EDIT.
// Source: postgres.go

// Package postgres is a generated GoMock package.
package postgres

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	sqlc "shopapi/internal/clients/postgres/sqlc"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockIQuerier is a mock of IQuerier interface.
type MockIQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockIQuerierMockRecorder
}

// MockIQuerierMockRecorder is the mock recorder for MockIQuerier.
type MockIQuerierMockRecorder struct {
	mock *MockIQuerier
}

// NewMockIQuerier creates a new mock instance.
func NewMockIQuerier(ctrl *gomock.Controller) *MockIQuerier {
	mock := &MockIQuerier{ctrl: ctrl}
	mock.recorder = &MockIQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIQuerier) EXPECT() *MockIQuerierMockRecorder {
	return m.recorder
}

// AddImage mocks base method.
func (m *MockIQuerier) AddImage(ctx context.Context, arg sqlc.AddImageParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddImage", ctx, arg)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddImage indicates an expected call of AddImage.
func (mr *MockIQuerierMockRecorder) AddImage(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddImage", reflect.TypeOf((*MockIQuerier)(nil).AddImage), ctx, arg)
}

// CalculateClientsWithAddress mocks base method.
func (m *MockIQuerier) CalculateClientsWithAddress(ctx context.Context, addressID int32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateClientsWithAddress", ctx, addressID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateClientsWithAddress indicates an expected call of CalculateClientsWithAddress.
func (mr *MockIQuerierMockRecorder) CalculateClientsWithAddress(ctx, addressID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateClientsWithAddress", reflect.TypeOf((*MockIQuerier)(nil).CalculateClientsWithAddress), ctx, addressID)
}

// CalculateSuppliersWithAddress mocks base method.
func (m *MockIQuerier) CalculateSuppliersWithAddress(ctx context.Context, addressID int32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateSuppliersWithAddress", ctx, addressID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateSuppliersWithAddress indicates an expected call of CalculateSuppliersWithAddress.
func (mr *MockIQuerierMockRecorder) CalculateSuppliersWithAddress(ctx, addressID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateSuppliersWithAddress", reflect.TypeOf((*MockIQuerier)(nil).CalculateSuppliersWithAddress), ctx, addressID)
}

// DecreaseProduct mocks base method.
func (m *MockIQuerier) DecreaseProduct(ctx context.Context, arg sqlc.DecreaseProductParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecreaseProduct", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecreaseProduct indicates an expected call of DecreaseProduct.
func (mr *MockIQuerierMockRecorder) DecreaseProduct(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecreaseProduct", reflect.TypeOf((*MockIQuerier)(nil).DecreaseProduct), ctx, arg)
}

// DeleteAddress mocks base method.
func (m *MockIQuerier) DeleteAddress(ctx context.Context, id int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAddress", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAddress indicates an expected call of DeleteAddress.
func (mr *MockIQuerierMockRecorder) DeleteAddress(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAddress", reflect.TypeOf((*MockIQuerier)(nil).DeleteAddress), ctx, id)
}

// DeleteClient mocks base method.
func (m *MockIQuerier) DeleteClient(ctx context.Context, uid uuid.UUID) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClient", ctx, uid)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteClient indicates an expected call of DeleteClient.
func (mr *MockIQuerierMockRecorder) DeleteClient(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClient", reflect.TypeOf((*MockIQuerier)(nil).DeleteClient), ctx, uid)
}

// DeleteImage mocks base method.
func (m *MockIQuerier) DeleteImage(ctx context.Context, uid uuid.UUID) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImage", ctx, uid)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockIQuerierMockRecorder) DeleteImage(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockIQuerier)(nil).DeleteImage), ctx, uid)
}

// DeleteProduct mocks base method.
func (m *MockIQuerier) DeleteProduct(ctx context.Context, uid uuid.UUID) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", ctx, uid)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockIQuerierMockRecorder) DeleteProduct(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockIQuerier)(nil).DeleteProduct), ctx, uid)
}

// DeleteSupplier mocks base method.
func (m *MockIQuerier) DeleteSupplier(ctx context.Context, uid uuid.UUID) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSupplier", ctx, uid)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSupplier indicates an expected call of DeleteSupplier.
func (mr *MockIQuerierMockRecorder) DeleteSupplier(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSupplier", reflect.TypeOf((*MockIQuerier)(nil).DeleteSupplier), ctx, uid)
}

// GetAllClients mocks base method.
func (m *MockIQuerier) GetAllClients(ctx context.Context) ([]sqlc.ClientDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllClients", ctx)
	ret0, _ := ret[0].([]sqlc.ClientDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllClients indicates an expected call of GetAllClients.
func (mr *MockIQuerierMockRecorder) GetAllClients(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllClients", reflect.TypeOf((*MockIQuerier)(nil).GetAllClients), ctx)
}

// GetAllProducts mocks base method.
func (m *MockIQuerier) GetAllProducts(ctx context.Context) ([]sqlc.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProducts", ctx)
	ret0, _ := ret[0].([]sqlc.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllProducts indicates an expected call of GetAllProducts.
func (mr *MockIQuerierMockRecorder) GetAllProducts(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProducts", reflect.TypeOf((*MockIQuerier)(nil).GetAllProducts), ctx)
}

// GetAllSuppliers mocks base method.
func (m *MockIQuerier) GetAllSuppliers(ctx context.Context) ([]sqlc.SupplierDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSuppliers", ctx)
	ret0, _ := ret[0].([]sqlc.SupplierDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSuppliers indicates an expected call of GetAllSuppliers.
func (mr *MockIQuerierMockRecorder) GetAllSuppliers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSuppliers", reflect.TypeOf((*MockIQuerier)(nil).GetAllSuppliers), ctx)
}

// GetClientsPage mocks base method.
func (m *MockIQuerier) GetClientsPage(ctx context.Context, arg sqlc.GetClientsPageParams) ([]sqlc.ClientDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientsPage", ctx, arg)
	ret0, _ := ret[0].([]sqlc.ClientDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientsPage indicates an expected call of GetClientsPage.
func (mr *MockIQuerierMockRecorder) GetClientsPage(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientsPage", reflect.TypeOf((*MockIQuerier)(nil).GetClientsPage), ctx, arg)
}

// GetClientsWithName mocks base method.
func (m *MockIQuerier) GetClientsWithName(ctx context.Context, arg sqlc.GetClientsWithNameParams) ([]sqlc.ClientDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientsWithName", ctx, arg)
	ret0, _ := ret[0].([]sqlc.ClientDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientsWithName indicates an expected call of GetClientsWithName.
func (mr *MockIQuerierMockRecorder) GetClientsWithName(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientsWithName", reflect.TypeOf((*MockIQuerier)(nil).GetClientsWithName), ctx, arg)
}

// GetImage mocks base method.
func (m *MockIQuerier) GetImage(ctx context.Context, uid uuid.UUID) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx, uid)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockIQuerierMockRecorder) GetImage(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockIQuerier)(nil).GetImage), ctx, uid)
}

// GetProduct mocks base method.
func (m *MockIQuerier) GetProduct(ctx context.Context, uid uuid.UUID) (sqlc.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", ctx, uid)
	ret0, _ := ret[0].(sqlc.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockIQuerierMockRecorder) GetProduct(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockIQuerier)(nil).GetProduct), ctx, uid)
}

// GetProductImage mocks base method.
func (m *MockIQuerier) GetProductImage(ctx context.Context, uid uuid.UUID) (sqlc.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductImage", ctx, uid)
	ret0, _ := ret[0].(sqlc.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductImage indicates an expected call of GetProductImage.
func (mr *MockIQuerierMockRecorder) GetProductImage(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductImage", reflect.TypeOf((*MockIQuerier)(nil).GetProductImage), ctx, uid)
}

// GetProductsPage mocks base method.
func (m *MockIQuerier) GetProductsPage(ctx context.Context, arg sqlc.GetProductsPageParams) ([]sqlc.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductsPage", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductsPage indicates an expected call of GetProductsPage.
func (mr *MockIQuerierMockRecorder) GetProductsPage(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsPage", reflect.TypeOf((*MockIQuerier)(nil).GetProductsPage), ctx, arg)
}

// GetSupplier mocks base method.
func (m *MockIQuerier) GetSupplier(ctx context.Context, uid uuid.UUID) (sqlc.SupplierDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupplier", ctx, uid)
	ret0, _ := ret[0].(sqlc.SupplierDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSupplier indicates an expected call of GetSupplier.
func (mr *MockIQuerierMockRecorder) GetSupplier(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupplier", reflect.TypeOf((*MockIQuerier)(nil).GetSupplier), ctx, uid)
}

// GetSuppliersPage mocks base method.
func (m *MockIQuerier) GetSuppliersPage(ctx context.Context, arg sqlc.GetSuppliersPageParams) ([]sqlc.SupplierDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuppliersPage", ctx, arg)
	ret0, _ := ret[0].([]sqlc.SupplierDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSuppliersPage indicates an expected call of GetSuppliersPage.
func (mr *MockIQuerierMockRecorder) GetSuppliersPage(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuppliersPage", reflect.TypeOf((*MockIQuerier)(nil).GetSuppliersPage), ctx, arg)
}

// InsertAddress mocks base method.
func (m *MockIQuerier) InsertAddress(ctx context.Context, arg sqlc.InsertAddressParams) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAddress", ctx, arg)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertAddress indicates an expected call of InsertAddress.
func (mr *MockIQuerierMockRecorder) InsertAddress(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAddress", reflect.TypeOf((*MockIQuerier)(nil).InsertAddress), ctx, arg)
}

// InsertClient mocks base method.
func (m *MockIQuerier) InsertClient(ctx context.Context, arg sqlc.InsertClientParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertClient", ctx, arg)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertClient indicates an expected call of InsertClient.
func (mr *MockIQuerierMockRecorder) InsertClient(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertClient", reflect.TypeOf((*MockIQuerier)(nil).InsertClient), ctx, arg)
}

// InsertProduct mocks base method.
func (m *MockIQuerier) InsertProduct(ctx context.Context, arg sqlc.InsertProductParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertProduct", ctx, arg)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertProduct indicates an expected call of InsertProduct.
func (mr *MockIQuerierMockRecorder) InsertProduct(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertProduct", reflect.TypeOf((*MockIQuerier)(nil).InsertProduct), ctx, arg)
}

// InsertSupplier mocks base method.
func (m *MockIQuerier) InsertSupplier(ctx context.Context, arg sqlc.InsertSupplierParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSupplier", ctx, arg)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertSupplier indicates an expected call of InsertSupplier.
func (mr *MockIQuerierMockRecorder) InsertSupplier(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSupplier", reflect.TypeOf((*MockIQuerier)(nil).InsertSupplier), ctx, arg)
}

// IsImageAndSupplierExists mocks base method.
func (m *MockIQuerier) IsImageAndSupplierExists(ctx context.Context, arg sqlc.IsImageAndSupplierExistsParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsImageAndSupplierExists", ctx, arg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsImageAndSupplierExists indicates an expected call of IsImageAndSupplierExists.
func (mr *MockIQuerierMockRecorder) IsImageAndSupplierExists(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsImageAndSupplierExists", reflect.TypeOf((*MockIQuerier)(nil).IsImageAndSupplierExists), ctx, arg)
}

// LockStockForUpdate mocks base method.
func (m *MockIQuerier) LockStockForUpdate(ctx context.Context, uid uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockStockForUpdate", ctx, uid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockStockForUpdate indicates an expected call of LockStockForUpdate.
func (mr *MockIQuerierMockRecorder) LockStockForUpdate(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockStockForUpdate", reflect.TypeOf((*MockIQuerier)(nil).LockStockForUpdate), ctx, uid)
}

// UpdateClientAddress mocks base method.
func (m *MockIQuerier) UpdateClientAddress(ctx context.Context, arg sqlc.UpdateClientAddressParams) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClientAddress", ctx, arg)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateClientAddress indicates an expected call of UpdateClientAddress.
func (mr *MockIQuerierMockRecorder) UpdateClientAddress(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClientAddress", reflect.TypeOf((*MockIQuerier)(nil).UpdateClientAddress), ctx, arg)
}

// UpdateImage mocks base method.
func (m *MockIQuerier) UpdateImage(ctx context.Context, arg sqlc.UpdateImageParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateImage", ctx, arg)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateImage indicates an expected call of UpdateImage.
func (mr *MockIQuerierMockRecorder) UpdateImage(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateImage", reflect.TypeOf((*MockIQuerier)(nil).UpdateImage), ctx, arg)
}

// UpdateSupplierAddress mocks base method.
func (m *MockIQuerier) UpdateSupplierAddress(ctx context.Context, arg sqlc.UpdateSupplierAddressParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSupplierAddress", ctx, arg)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSupplierAddress indicates an expected call of UpdateSupplierAddress.
func (mr *MockIQuerierMockRecorder) UpdateSupplierAddress(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSupplierAddress", reflect.TypeOf((*MockIQuerier)(nil).UpdateSupplierAddress), ctx, arg)
}

// MockIDB is a mock of IDB interface.
type MockIDB struct {
	ctrl     *gomock.Controller
	recorder *MockIDBMockRecorder
}

// MockIDBMockRecorder is the mock recorder for MockIDB.
type MockIDBMockRecorder struct {
	mock *MockIDB
}

// NewMockIDB creates a new mock instance.
func NewMockIDB(ctrl *gomock.Controller) *MockIDB {
	mock := &MockIDB{ctrl: ctrl}
	mock.recorder = &MockIDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDB) EXPECT() *MockIDBMockRecorder {
	return m.recorder
}

// CtxWithCancel mocks base method.
func (m *MockIDB) CtxWithCancel() (context.Context, context.CancelFunc) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CtxWithCancel")
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(context.CancelFunc)
	return ret0, ret1
}

// CtxWithCancel indicates an expected call of CtxWithCancel.
func (mr *MockIDBMockRecorder) CtxWithCancel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CtxWithCancel", reflect.TypeOf((*MockIDB)(nil).CtxWithCancel))
}

// ExecTx mocks base method.
func (m *MockIDB) ExecTx(arg0 *sql.TxOptions, arg1 func(context.Context, IQuerier) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecTx", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecTx indicates an expected call of ExecTx.
func (mr *MockIDBMockRecorder) ExecTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecTx", reflect.TypeOf((*MockIDB)(nil).ExecTx), arg0, arg1)
}

// Querier mocks base method.
func (m *MockIDB) Querier() IQuerier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Querier")
	ret0, _ := ret[0].(IQuerier)
	return ret0
}

// Querier indicates an expected call of Querier.
func (mr *MockIDBMockRecorder) Querier() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Querier", reflect.TypeOf((*MockIDB)(nil).Querier))
}
